backend:
  # Use netlify identity as backend
  name: git-gateway
  branch: main
  ### enable below lines for github integration ###
  # name: github
  # repo: https://github.com/webdigga/ear-protectors
media_folder: "src/static/img"
public_folder: "/static/img"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true
# publish_mode: editorial_workflow
collections:
  - label: "Article"
    name: "article"
    folder: "src/posts"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "type"
        name: "type"
        create: true
        options: ["article", "blog", "privacy"]
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["article", "blog", "privacy"]
      - label: "Hero image"
        name: "heroImage"
        widget: "image"
        choose_url: true
        required: false
        media_library:
          config:
            multiple: false
      - label: "Highlights box"
        name: "highlightsBoxes"
        widget: "list"
        fields:
          - { label: Title, name: title, widget: string }
          - label: Highlights list item
            name: highlightsListItem
            widget: list
            fields:
              - { label: Highlight, name: highlight, widget: string }
      - { label: "Button one text", name: "buttonOneText", widget: "string", required: false }
      - { label: "Button one URL", name: "buttonOneUrl", widget: "string", required: false }
      - { label: "Button two text", name: "buttonTwoText", widget: "string", required: false }
      - { label: "Button two URL", name: "buttonTwoUrl", widget: "string", required: false }
  - label: "ProductCard"
    name: "productCard"
    folder: "src/productCards"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Article Link", name: "articleLink", widget: "string" }
      - { label: "Order", name: "order", widget: "number" }
  - label: "Hero"
    name: "hero"
    folder: "src/hero"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Button one text", name: "buttonOneText", widget: "string" }
      - { label: "Button one URL", name: "buttonOneUrl", widget: "string" }
      - { label: "Button two text", name: "buttonTwoText", widget: "string" }
      - { label: "Button two URL", name: "buttonTwoUrl", widget: "string" }
      - label: "Image"
        name: "image"
        widget: "image"
        choose_url: true
        media_library:
          config:
            multiple: false
      - { label: "Image alt", name: "imageAlt", widget: "string" }
  - label: "Call to action"
    name: "callToAction"
    folder: "src/callToAction"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Button text", name: "buttonText", widget: "string" }
      - { label: "Button URL", name: "buttonUrl", widget: "string" }
  - label: "Homepage spiel"
    name: "homepageSpiel"
    folder: "src/homepageSpiel"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "markdown" }
  - label: "Settings"
    name: "settings"
    editor:
      preview: false
    files:
      - label: "Navigation"
        name: "items"
        file: "src/_data/navigation.yaml"
        fields:
          - label: Nav Items
            name: items
            widget: list
            allow_add: false
            collapsed: false
            fields:
              - { label: Title, name: text, widget: string }
              - { label: URL, name: url, widget: string }
      - label: "Meta Settings"
        name: "settings"
        file: "src/_data/settings.yaml"
        fields:
          - { label: Site Name, name: siteName, widget: string }
          - { label: Title, name: title, widget: string }
          - { label: Author, name: author, widget: string }
          - { label: URL, name: url, widget: string }
          - { label: Powered by, name: poweredBy, widget: string }
          - { label: Description, name: description, widget: string }
          - { label: Type (type of template), name: type, widget: string }
          - { label: Logo (Alt), name: logoAlt, widget: string }
          - label: "Logo (URL)"
            name: "logoUrl"
            widget: "image"
            choose_url: true
            media_library:
              config:
                multiple: false
